/* Generated By:JavaCC: Do not edit this line. StandardTokenizerConstants.java */
package com.lucene.analysis.standard;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StandardTokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHANUM = 1;
  /** RegularExpression Id. */
  int APOSTROPHE = 2;
  /** RegularExpression Id. */
  int ACRONYM = 3;
  /** RegularExpression Id. */
  int COMPANY = 4;
  /** RegularExpression Id. */
  int EMAIL = 5;
  /** RegularExpression Id. */
  int HOST = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int P = 8;
  /** RegularExpression Id. */
  int HAS_DIGIT = 9;
  /** RegularExpression Id. */
  int ALPHA = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int NOISE = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ALPHANUM>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<DIGIT>",
    "<NOISE>",
  };

}
