/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package com.lucene.queryParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int _ALPHA_CHAR = 1;
  /** RegularExpression Id. */
  int _NUM_CHAR = 2;
  /** RegularExpression Id. */
  int _ALPHANUM_CHAR = 3;
  /** RegularExpression Id. */
  int _IDENTIFIER_CHAR = 4;
  /** RegularExpression Id. */
  int _IDENTIFIER = 5;
  /** RegularExpression Id. */
  int _NEWLINE = 6;
  /** RegularExpression Id. */
  int _WHITESPACE = 7;
  /** RegularExpression Id. */
  int _QCHAR = 8;
  /** RegularExpression Id. */
  int _RESTOFLINE = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int LPAREN = 15;
  /** RegularExpression Id. */
  int RPAREN = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int CARAT = 18;
  /** RegularExpression Id. */
  int STAR = 19;
  /** RegularExpression Id. */
  int QUOTED = 20;
  /** RegularExpression Id. */
  int NUMBER = 21;
  /** RegularExpression Id. */
  int TERM = 22;
  /** RegularExpression Id. */
  int FUZZY = 23;
  /** RegularExpression Id. */
  int WILDTERM = 24;
  /** RegularExpression Id. */
  int RANGEIN = 25;
  /** RegularExpression Id. */
  int RANGEEX = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<_ALPHA_CHAR>",
    "<_NUM_CHAR>",
    "<_ALPHANUM_CHAR>",
    "<_IDENTIFIER_CHAR>",
    "<_IDENTIFIER>",
    "<_NEWLINE>",
    "<_WHITESPACE>",
    "<_QCHAR>",
    "<_RESTOFLINE>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "\"+\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"^\"",
    "\"*\"",
    "<QUOTED>",
    "<NUMBER>",
    "<TERM>",
    "\"~\"",
    "<WILDTERM>",
    "<RANGEIN>",
    "<RANGEEX>",
  };

}
