/* Generated By:JavaCC: Do not edit this line. HTMLParserConstants.java */
package demo.HTMLParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HTMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TagName = 1;
  /** RegularExpression Id. */
  int DeclName = 2;
  /** RegularExpression Id. */
  int Comment1 = 3;
  /** RegularExpression Id. */
  int Comment2 = 4;
  /** RegularExpression Id. */
  int Word = 5;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int Entity = 8;
  /** RegularExpression Id. */
  int Space = 9;
  /** RegularExpression Id. */
  int SP = 10;
  /** RegularExpression Id. */
  int Punct = 11;
  /** RegularExpression Id. */
  int ArgName = 12;
  /** RegularExpression Id. */
  int ArgEquals = 13;
  /** RegularExpression Id. */
  int TagEnd = 14;
  /** RegularExpression Id. */
  int ArgValue = 15;
  /** RegularExpression Id. */
  int ArgQuote1 = 16;
  /** RegularExpression Id. */
  int ArgQuote2 = 17;
  /** RegularExpression Id. */
  int Quote1Text = 19;
  /** RegularExpression Id. */
  int CloseQuote1 = 20;
  /** RegularExpression Id. */
  int Quote2Text = 21;
  /** RegularExpression Id. */
  int CloseQuote2 = 22;
  /** RegularExpression Id. */
  int CommentText1 = 23;
  /** RegularExpression Id. */
  int CommentEnd1 = 24;
  /** RegularExpression Id. */
  int CommentText2 = 25;
  /** RegularExpression Id. */
  int CommentEnd2 = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinTag = 1;
  /** Lexical state. */
  int AfterEquals = 2;
  /** Lexical state. */
  int WithinQuote1 = 3;
  /** Lexical state. */
  int WithinQuote2 = 4;
  /** Lexical state. */
  int WithinComment1 = 5;
  /** Lexical state. */
  int WithinComment2 = 6;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<TagName>",
    "<DeclName>",
    "\"<!--\"",
    "\"<!\"",
    "<Word>",
    "<LET>",
    "<NUM>",
    "<Entity>",
    "<Space>",
    "<SP>",
    "<Punct>",
    "<ArgName>",
    "\"=\"",
    "<TagEnd>",
    "<ArgValue>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<token of kind 18>",
    "<Quote1Text>",
    "<CloseQuote1>",
    "<Quote2Text>",
    "<CloseQuote2>",
    "<CommentText1>",
    "\"-->\"",
    "<CommentText2>",
    "\">\"",
  };

}
